/*
 * test_cred_store_integration.c -- cred_store integration test with
 * a real DER cert produced by the Python FakeNdesCA harness.
 *
 * Tests:
 *   1. cred_store_parse_not_after() on a cert issued by FakeNdesCA returns
 *      the epoch that matches Python's calendar.timegm computation.
 *   2. Save {cert, key, ca_chain} -> Load -> byte-for-byte equality on all
 *      fields, not_after matches fixture epoch.
 *   3. Parse after clear returns NOT_FOUND.
 *   4. parse_not_after returns correct epoch even without saving.
 *   5. save/load preserves large ca_chain blob without truncation.
 *
 * Fixtures are generated by test/scripts/test_scep_protocol_e2e.py's
 * FakeNdesCA (run once, committed to the repo).  To regenerate:
 *
 *   cd /root/esp-tty
 *   venv/bin/python test/scripts/regen_cred_store_fixtures.py
 *
 * Design choice: pre-committed fixtures rather than a shell wrapper because:
 *   - Keeps the native test hermetic (no Python dependency at test-run time).
 *   - Avoids brittle pipe between Python and PlatformIO's test runner.
 *   - Fixtures capture a concrete issuer cert, making assertion failures easier
 *     to diagnose than with random-key fixtures generated on every run.
 *
 * Compiled with:
 *   -DCRED_STORE_NATIVE_TEST  (in-memory NVS backend)
 *   -DUNIT_TEST
 */

#define CRED_STORE_NATIVE_TEST  1

#include "unity.h"
#include "cred_store.h"

#include <string.h>
#include <stdint.h>

/* --------------------------------------------------------------------------
 * Fixture: cert DER issued by FakeNdesCA for CN=esp-tty-integ-test
 *
 * Generated by:
 *   venv/bin/python test/scripts/regen_cred_store_fixtures.py
 *
 * NotAfter: 2027-05-13 21:52:30 UTC  ->  epoch 1810245150
 * -------------------------------------------------------------------------- */
static const uint8_t fixture_cert_der[] = {
    0x30, 0x82, 0x01, 0x33, 0x30, 0x81, 0xda, 0xa0, 0x03, 0x02, 0x01, 0x02,
    0x02, 0x14, 0x69, 0xbb, 0x97, 0x2d, 0x33, 0x10, 0xf0, 0x08, 0x2a, 0x0b,
    0xb6, 0xc7, 0xed, 0x2a, 0x81, 0x28, 0xc9, 0x18, 0xe4, 0xea, 0x30, 0x0a,
    0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x04, 0x03, 0x02, 0x30, 0x17,
    0x31, 0x15, 0x30, 0x13, 0x06, 0x03, 0x55, 0x04, 0x03, 0x0c, 0x0c, 0x46,
    0x61, 0x6b, 0x65, 0x2d, 0x4e, 0x44, 0x45, 0x53, 0x2d, 0x43, 0x41, 0x30,
    0x1e, 0x17, 0x0d, 0x32, 0x36, 0x30, 0x35, 0x31, 0x33, 0x32, 0x31, 0x35,
    0x32, 0x33, 0x30, 0x5a, 0x17, 0x0d, 0x32, 0x37, 0x30, 0x35, 0x31, 0x33,
    0x32, 0x31, 0x35, 0x32, 0x33, 0x30, 0x5a, 0x30, 0x1d, 0x31, 0x1b, 0x30,
    0x19, 0x06, 0x03, 0x55, 0x04, 0x03, 0x0c, 0x12, 0x65, 0x73, 0x70, 0x2d,
    0x74, 0x74, 0x79, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x2d, 0x74, 0x65,
    0x73, 0x74, 0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86, 0x48, 0xce,
    0x3d, 0x02, 0x01, 0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01,
    0x07, 0x03, 0x42, 0x00, 0x04, 0x2c, 0x36, 0xeb, 0x81, 0x33, 0x33, 0x25,
    0x3a, 0x42, 0x34, 0x0a, 0x11, 0xc6, 0x7b, 0x99, 0xf6, 0xe2, 0x77, 0x86,
    0x03, 0x19, 0x33, 0x9c, 0x6f, 0x8f, 0x03, 0xf6, 0x1b, 0xc9, 0x34, 0x6f,
    0xb1, 0x27, 0xd3, 0xe4, 0x98, 0xac, 0x65, 0x4c, 0xfe, 0x38, 0xca, 0x35,
    0x88, 0x8b, 0xd7, 0x93, 0xe0, 0x84, 0x34, 0x9d, 0x4d, 0x77, 0x0e, 0x9b,
    0xae, 0x09, 0x98, 0xc5, 0x5f, 0xa7, 0xfa, 0xe8, 0x77, 0x30, 0x0a, 0x06,
    0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x04, 0x03, 0x02, 0x03, 0x48, 0x00,
    0x30, 0x45, 0x02, 0x21, 0x00, 0x87, 0x4d, 0x7a, 0x49, 0x3c, 0xef, 0x16,
    0xaf, 0x9f, 0x85, 0x52, 0xdc, 0x1e, 0xea, 0xa8, 0x6d, 0x67, 0xb4, 0x09,
    0x79, 0xc5, 0x2d, 0xa0, 0xb4, 0x07, 0xaa, 0x77, 0x8d, 0x7e, 0xa0, 0x49,
    0x53, 0x02, 0x20, 0x01, 0x85, 0x5c, 0x41, 0x13, 0xaf, 0x7f, 0xb1, 0x50,
    0x38, 0x59, 0x77, 0x27, 0x5c, 0x66, 0x60, 0xf1, 0x29, 0xd8, 0x34, 0x76,
    0x95, 0x02, 0xd8, 0xb0, 0x9a, 0x7e, 0xbd, 0xee, 0x2d, 0x00, 0x3c,
};
static const size_t fixture_cert_der_len = 311;

static const uint8_t fixture_key_der[] = {
    0x30, 0x77, 0x02, 0x01, 0x01, 0x04, 0x20, 0xc5, 0x99, 0x64, 0x1b, 0x9d,
    0xf8, 0x7a, 0xf0, 0xaf, 0x19, 0x4a, 0x0f, 0x9b, 0x49, 0x8e, 0xb9, 0x74,
    0x02, 0x17, 0x53, 0x50, 0x4b, 0xe2, 0x0a, 0x7f, 0x3a, 0xb3, 0x5a, 0x6c,
    0x0e, 0xa8, 0x62, 0xa0, 0x0a, 0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d,
    0x03, 0x01, 0x07, 0xa1, 0x44, 0x03, 0x42, 0x00, 0x04, 0x2c, 0x36, 0xeb,
    0x81, 0x33, 0x33, 0x25, 0x3a, 0x42, 0x34, 0x0a, 0x11, 0xc6, 0x7b, 0x99,
    0xf6, 0xe2, 0x77, 0x86, 0x03, 0x19, 0x33, 0x9c, 0x6f, 0x8f, 0x03, 0xf6,
    0x1b, 0xc9, 0x34, 0x6f, 0xb1, 0x27, 0xd3, 0xe4, 0x98, 0xac, 0x65, 0x4c,
    0xfe, 0x38, 0xca, 0x35, 0x88, 0x8b, 0xd7, 0x93, 0xe0, 0x84, 0x34, 0x9d,
    0x4d, 0x77, 0x0e, 0x9b, 0xae, 0x09, 0x98, 0xc5, 0x5f, 0xa7, 0xfa, 0xe8,
    0x77,
};
static const size_t fixture_key_der_len = 121;

/* Expected NotAfter epoch: 2027-05-13 21:52:30 UTC */
#define FIXTURE_NOT_AFTER_EPOCH  UINT64_C(1810245150)

/* A small fake CA chain (PEM-like string for testing storage) */
static const char fixture_ca_chain[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBMzCB2qADAgECAgRl4...SCEP-Integration-Test-CA\n"
    "-----END CERTIFICATE-----\n";

/* --------------------------------------------------------------------------
 * setUp / tearDown
 * -------------------------------------------------------------------------- */
void setUp(void)    { cred_store_clear(); }
void tearDown(void) {}

/* --------------------------------------------------------------------------
 * Test 1: parse_not_after on FakeNdesCA-issued cert returns correct epoch
 * -------------------------------------------------------------------------- */
static void test_parse_not_after_fake_ndes_ca_cert(void)
{
    uint64_t epoch = 0;
    esp_err_t err = cred_store_parse_not_after(fixture_cert_der,
                                               fixture_cert_der_len,
                                               &epoch);
    TEST_ASSERT_EQUAL_INT(ESP_OK, err);
    TEST_ASSERT_EQUAL_UINT64(FIXTURE_NOT_AFTER_EPOCH, epoch);
}

/* --------------------------------------------------------------------------
 * Test 2: save + load preserves cert and key byte-for-byte
 * -------------------------------------------------------------------------- */
static void test_save_load_real_cert_and_key(void)
{
    cred_store_t in;
    memset(&in, 0, sizeof(in));

    /* Device key */
    TEST_ASSERT_LESS_OR_EQUAL(CRED_DEV_KEY_MAX, fixture_key_der_len);
    in.dev_key_len = fixture_key_der_len;
    memcpy(in.dev_key, fixture_key_der, fixture_key_der_len);

    /* Device cert */
    TEST_ASSERT_LESS_OR_EQUAL(CRED_DEV_CERT_MAX, fixture_cert_der_len);
    in.dev_cert_len = fixture_cert_der_len;
    memcpy(in.dev_cert, fixture_cert_der, fixture_cert_der_len);

    /* CA chain */
    size_t chain_len = strlen(fixture_ca_chain);
    TEST_ASSERT_LESS_OR_EQUAL(CRED_CA_CHAIN_MAX, chain_len);
    in.ca_chain_len = chain_len;
    memcpy(in.ca_chain, fixture_ca_chain, chain_len);

    /* not_after from parsed cert */
    in.not_after = FIXTURE_NOT_AFTER_EPOCH;

    esp_err_t err = cred_store_save(&in);
    TEST_ASSERT_EQUAL_INT(ESP_OK, err);

    cred_store_t out;
    memset(&out, 0, sizeof(out));
    err = cred_store_load(&out);
    TEST_ASSERT_EQUAL_INT(ESP_OK, err);

    /* Verify key byte-for-byte */
    TEST_ASSERT_EQUAL_size_t(fixture_key_der_len, out.dev_key_len);
    TEST_ASSERT_EQUAL_MEMORY(fixture_key_der, out.dev_key, fixture_key_der_len);

    /* Verify cert byte-for-byte */
    TEST_ASSERT_EQUAL_size_t(fixture_cert_der_len, out.dev_cert_len);
    TEST_ASSERT_EQUAL_MEMORY(fixture_cert_der, out.dev_cert, fixture_cert_der_len);

    /* Verify CA chain */
    TEST_ASSERT_EQUAL_size_t(chain_len, out.ca_chain_len);
    TEST_ASSERT_EQUAL_MEMORY(fixture_ca_chain, out.ca_chain, chain_len);

    /* Verify not_after */
    TEST_ASSERT_EQUAL_UINT64(FIXTURE_NOT_AFTER_EPOCH, out.not_after);
}

/* --------------------------------------------------------------------------
 * Test 3: clear after save -> load returns NOT_FOUND
 * -------------------------------------------------------------------------- */
static void test_clear_after_real_cert_save(void)
{
    cred_store_t in;
    memset(&in, 0, sizeof(in));
    in.dev_cert_len = fixture_cert_der_len;
    memcpy(in.dev_cert, fixture_cert_der, fixture_cert_der_len);
    in.dev_key_len  = fixture_key_der_len;
    memcpy(in.dev_key, fixture_key_der, fixture_key_der_len);
    in.ca_chain_len = 1; in.ca_chain[0] = 0xAB;
    in.not_after    = FIXTURE_NOT_AFTER_EPOCH;

    TEST_ASSERT_EQUAL_INT(ESP_OK, cred_store_save(&in));

    /* Verify it's there */
    cred_store_t out;
    TEST_ASSERT_EQUAL_INT(ESP_OK, cred_store_load(&out));

    /* Clear */
    TEST_ASSERT_EQUAL_INT(ESP_OK, cred_store_clear());

    /* Load must fail */
    TEST_ASSERT_EQUAL_INT(ESP_ERR_NVS_NOT_FOUND, cred_store_load(&out));
}

/* --------------------------------------------------------------------------
 * Test 4: parse_not_after is pure (doesn't require save/load)
 * -------------------------------------------------------------------------- */
static void test_parse_not_after_is_pure_function(void)
{
    /* Don't call cred_store_save -- parse should work on raw DER regardless */
    uint64_t epoch = 0;
    esp_err_t err = cred_store_parse_not_after(fixture_cert_der,
                                               fixture_cert_der_len,
                                               &epoch);
    TEST_ASSERT_EQUAL_INT(ESP_OK, err);
    TEST_ASSERT_EQUAL_UINT64(FIXTURE_NOT_AFTER_EPOCH, epoch);

    /* Load should still return NOT_FOUND (no save was called) */
    cred_store_t out;
    TEST_ASSERT_EQUAL_INT(ESP_ERR_NVS_NOT_FOUND, cred_store_load(&out));
}

/* --------------------------------------------------------------------------
 * Test 5: save/load preserves large ca_chain blob without truncation
 * -------------------------------------------------------------------------- */
static void test_large_ca_chain_preserved(void)
{
    /* Build a ca_chain close to CRED_CA_CHAIN_MAX */
    cred_store_t in;
    memset(&in, 0, sizeof(in));
    in.dev_cert_len = fixture_cert_der_len;
    memcpy(in.dev_cert, fixture_cert_der, fixture_cert_der_len);
    in.dev_key_len  = fixture_key_der_len;
    memcpy(in.dev_key, fixture_key_der, fixture_key_der_len);

    /* Fill ca_chain with a recognizable pattern up to 1 KB */
    size_t chain_sz = 1024;
    for (size_t i = 0; i < chain_sz; i++) {
        in.ca_chain[i] = (uint8_t)(i & 0xFF);
    }
    in.ca_chain_len = chain_sz;
    in.not_after    = FIXTURE_NOT_AFTER_EPOCH;

    TEST_ASSERT_EQUAL_INT(ESP_OK, cred_store_save(&in));

    cred_store_t out;
    memset(&out, 0, sizeof(out));
    TEST_ASSERT_EQUAL_INT(ESP_OK, cred_store_load(&out));

    TEST_ASSERT_EQUAL_size_t(chain_sz, out.ca_chain_len);
    TEST_ASSERT_EQUAL_MEMORY(in.ca_chain, out.ca_chain, chain_sz);
}

/* --------------------------------------------------------------------------
 * Test 6: parse_not_after on a cert with truncated DER -> ESP_FAIL
 * -------------------------------------------------------------------------- */
static void test_parse_truncated_cert_returns_fail(void)
{
    uint64_t epoch = 0;
    /* Feed only the first half of the cert DER */
    esp_err_t err = cred_store_parse_not_after(fixture_cert_der,
                                               fixture_cert_der_len / 2,
                                               &epoch);
    TEST_ASSERT_NOT_EQUAL(ESP_OK, err);
}

/* --------------------------------------------------------------------------
 * Test 7: double save overwrites previous data
 * -------------------------------------------------------------------------- */
static void test_double_save_overwrites_with_real_cert(void)
{
    /* First save: fake data */
    cred_store_t a;
    memset(&a, 0, sizeof(a));
    a.dev_key_len  = 1; a.dev_key[0]  = 0xDE;
    a.dev_cert_len = 1; a.dev_cert[0] = 0xAD;
    a.ca_chain_len = 1; a.ca_chain[0] = 0xBE;
    a.not_after    = 0;
    TEST_ASSERT_EQUAL_INT(ESP_OK, cred_store_save(&a));

    /* Second save: real cert+key */
    cred_store_t b;
    memset(&b, 0, sizeof(b));
    b.dev_cert_len = fixture_cert_der_len;
    memcpy(b.dev_cert, fixture_cert_der, fixture_cert_der_len);
    b.dev_key_len  = fixture_key_der_len;
    memcpy(b.dev_key, fixture_key_der, fixture_key_der_len);
    b.ca_chain_len = 2; b.ca_chain[0] = 0xCA; b.ca_chain[1] = 0xFE;
    b.not_after    = FIXTURE_NOT_AFTER_EPOCH;
    TEST_ASSERT_EQUAL_INT(ESP_OK, cred_store_save(&b));

    cred_store_t out;
    memset(&out, 0, sizeof(out));
    TEST_ASSERT_EQUAL_INT(ESP_OK, cred_store_load(&out));

    TEST_ASSERT_EQUAL_size_t(fixture_cert_der_len, out.dev_cert_len);
    TEST_ASSERT_EQUAL_MEMORY(fixture_cert_der, out.dev_cert, fixture_cert_der_len);
    TEST_ASSERT_EQUAL_UINT64(FIXTURE_NOT_AFTER_EPOCH, out.not_after);
}

/* --------------------------------------------------------------------------
 * main
 * -------------------------------------------------------------------------- */
int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_parse_not_after_fake_ndes_ca_cert);
    RUN_TEST(test_save_load_real_cert_and_key);
    RUN_TEST(test_clear_after_real_cert_save);
    RUN_TEST(test_parse_not_after_is_pure_function);
    RUN_TEST(test_large_ca_chain_preserved);
    RUN_TEST(test_parse_truncated_cert_returns_fail);
    RUN_TEST(test_double_save_overwrites_with_real_cert);
    return UNITY_END();
}
