#!/usr/bin/env python3
"""
regen_cred_store_fixtures.py -- Regenerate DER fixtures for test_cred_store_integration.

Uses FakeNdesCA from test_scep_protocol_e2e.py to perform a complete SCEP
enrollment, then embeds the resulting cert + key into:
  test/native/test_cred_store_integration/test_cred_store_integration.c

Run this only when you need to refresh the fixtures (e.g., if the FakeNdesCA
cert structure changes).  The C file is committed so native tests don't require
Python at run time.

Usage:
    cd /root/esp-tty
    venv/bin/python test/scripts/regen_cred_store_fixtures.py
"""

import os
import sys
import calendar
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from test_scep_protocol_e2e import FakeNdesCA, SCEPClient
from cryptography.hazmat.primitives.serialization import (
    Encoding, PrivateFormat, NoEncryption,
)

CHALLENGE = "FFC9708138742EC99A8CDF837A9F4CEA"
CN        = "esp-tty-integ-test"

FIXTURES_DIR = os.path.join(HERE, "..", "native",
                             "test_cred_store_integration", "fixtures")
C_FILE = os.path.join(HERE, "..", "native",
                       "test_cred_store_integration",
                       "test_cred_store_integration.c")


def bytes_to_c_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        row   = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {row},")
    lines.append("};")
    lines.append(f"static const size_t {name}_len = {len(data)};")
    return "\n".join(lines)


def main():
    print("Enrolling with FakeNdesCA...")
    ca     = FakeNdesCA(expect_challenge_password=CHALLENGE)
    client = SCEPClient(cn=CN, challenge_password=CHALLENGE)
    client.generate_key()

    bundle  = client.parse_getcacert(ca.respond_get_cacert())
    pkcsreq = client.build_pkcsreq(bundle["ra_enc_cert"])
    certrep = ca.respond_pki_operation(pkcsreq)
    client.parse_certrep(certrep)

    cert = client.issued_cert
    key  = client._private_key

    cert_der = cert.public_bytes(Encoding.DER)
    key_der  = key.private_bytes(Encoding.DER, PrivateFormat.TraditionalOpenSSL,
                                  NoEncryption())

    not_after       = cert.not_valid_after_utc
    not_after_epoch = calendar.timegm(not_after.utctimetuple())

    print(f"  cert_der: {len(cert_der)} bytes")
    print(f"  key_der:  {len(key_der)} bytes")
    print(f"  not_after: {not_after} -> epoch {not_after_epoch}")

    # ── Write binary fixtures ──────────────────────────────────────────────
    os.makedirs(FIXTURES_DIR, exist_ok=True)
    with open(os.path.join(FIXTURES_DIR, "cert.der"), "wb") as f:
        f.write(cert_der)
    with open(os.path.join(FIXTURES_DIR, "key.der"), "wb") as f:
        f.write(key_der)
    with open(os.path.join(FIXTURES_DIR, "expected_not_after.txt"), "w") as f:
        f.write(str(not_after_epoch))
    with open(os.path.join(FIXTURES_DIR, "ca_chain.pem"), "wb") as f:
        f.write(ca.ca_cert.public_bytes(Encoding.PEM))

    print(f"Binary fixtures written to {FIXTURES_DIR}")

    # ── Patch the C file ────────────────────────────────────────────────────
    # Find the fixture section delimiters in the C file and replace between them.
    MARKER_START = "/* --------------------------------------------------------------------------\n * Fixture:"
    MARKER_END   = "/* --------------------------------------------------------------------------\n * setUp"

    with open(C_FILE) as f:
        src = f.read()

    start_idx = src.find(MARKER_START)
    end_idx   = src.find(MARKER_END)
    if start_idx == -1 or end_idx == -1:
        print("WARNING: Could not find fixture markers in C file; printing new fixture only.")
        print(bytes_to_c_array("fixture_cert_der", cert_der))
        print()
        print(bytes_to_c_array("fixture_key_der", key_der))
        print()
        print(f"#define FIXTURE_NOT_AFTER_EPOCH  UINT64_C({not_after_epoch})")
        return

    new_fixture_block = f"""{MARKER_START[:-1]}
 * Fixture: cert DER issued by FakeNdesCA for CN={CN}
 *
 * Generated by:
 *   venv/bin/python test/scripts/regen_cred_store_fixtures.py
 *
 * NotAfter: {not_after}  ->  epoch {not_after_epoch}
 * -------------------------------------------------------------------------- */
{bytes_to_c_array("fixture_cert_der", cert_der)}

{bytes_to_c_array("fixture_key_der", key_der)}

/* Expected NotAfter epoch: {not_after} */
#define FIXTURE_NOT_AFTER_EPOCH  UINT64_C({not_after_epoch})

"""

    new_src = src[:start_idx] + new_fixture_block + src[end_idx:]
    with open(C_FILE, "w") as f:
        f.write(new_src)

    print(f"C fixture updated in {C_FILE}")


if __name__ == "__main__":
    main()
