#!/usr/bin/env bash
# test/scripts/test_clean_build.sh — Clean-build reproducibility test
#
# 1. Wipes build cache (managed_components, dependencies.lock, .pio/build/wokwi)
# 2. Creates a minimal main/config.h from main/config.h.example (saves/restores original)
# 3. Runs `pio run -e wokwi`  — must succeed
# 4. Runs `pio test -e native` — must show all native tests passing
# 5. Restores original main/config.h
# 6. Prints PASS/FAIL with reason; exits 0/1

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

CONFIG_H="$PROJECT_DIR/main/config.h"
CONFIG_EXAMPLE="$PROJECT_DIR/main/config.h.example"
CONFIG_BACKUP="/tmp/esp-tty-clean-build-config.h.bak"

PASS=0
FAIL_REASON=""

fail() {
    FAIL_REASON="$1"
    PASS=1
}

cleanup() {
    # Restore config.h if we saved it
    if [[ -f "$CONFIG_BACKUP" ]]; then
        cp "$CONFIG_BACKUP" "$CONFIG_H"
        rm -f "$CONFIG_BACKUP"
        echo "[clean_build] Restored original config.h"
    fi
}
trap cleanup EXIT

echo "[clean_build] ── Step 1: wipe build artefacts ──────────────────────────"
rm -rf "$PROJECT_DIR/managed_components" \
       "$PROJECT_DIR/dependencies.lock" \
       "$PROJECT_DIR/.pio/build/wokwi"
echo "[clean_build] Build cache cleared"

echo "[clean_build] ── Step 2: set up config.h ──────────────────────────────"
if [[ -f "$CONFIG_H" ]]; then
    cp "$CONFIG_H" "$CONFIG_BACKUP"
    echo "[clean_build] Saved existing config.h to $CONFIG_BACKUP"
fi

# Build a minimal config.h that satisfies all compile-time #defines.
# We use obviously-placeholder values so no real credentials are needed.
cat > "$CONFIG_H" <<'CONFEOF'
/*
 * config.h — auto-generated by test_clean_build.sh (minimal placeholder)
 * Do NOT commit this file.
 */
#pragma once

#define WIFI_SSID              "test-ssid"
#define WIFI_PASS              "test-pass"
#define SSH_PORT               2222
#define AUTHORIZED_PUBKEYS     "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4f placeholder"
#define OTA_AUTHORIZED_PUBKEY  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4f placeholder"
CONFEOF
echo "[clean_build] Minimal config.h written"

echo "[clean_build] ── Step 3: pio run -e wokwi ──────────────────────────────"
if ! pio run -e wokwi; then
    fail "pio run -e wokwi FAILED"
fi

if [[ $PASS -eq 0 ]]; then
    echo "[clean_build] ── Step 4: pio test -e native ───────────────────────────"
    # Capture native test output
    NATIVE_OUT=$(pio test -e native 2>&1)
    echo "$NATIVE_OUT"

    # Extract the summary line, e.g. "45 test cases: 45 succeeded"
    if echo "$NATIVE_OUT" | grep -qE '[0-9]+ test cases: [0-9]+ succeeded'; then
        SUMMARY=$(echo "$NATIVE_OUT" | grep -E '[0-9]+ test cases: [0-9]+ succeeded' | tail -1)
        # Summary line format: "=== N test cases: M succeeded ..."
        # Extract the first number (total) and "M succeeded"
        TOTAL=$(echo "$SUMMARY" | grep -oE '[0-9]+ test cases' | grep -oE '^[0-9]+')
        PASSED=$(echo "$SUMMARY" | grep -oE '[0-9]+ succeeded' | grep -oE '^[0-9]+')
        if [[ "$TOTAL" != "$PASSED" ]]; then
            fail "Native tests: $PASSED/$TOTAL passed (expected all)"
        else
            echo "[clean_build] Native tests: $PASSED/$TOTAL passed"
        fi
    else
        fail "Native test summary line not found in output"
    fi
fi

if [[ $PASS -eq 0 ]]; then
    echo "[clean_build] ── Step 5: second pio run -e wokwi (patch idempotency) ──"
    # Running again without cleaning verifies that the "already applied" detection
    # in apply_managed_patches_cmake.py works correctly and does not error.
    if ! pio run -e wokwi; then
        fail "pio run -e wokwi (second, incremental) FAILED"
    fi
    echo "[clean_build] Patch idempotency check: PASS"
fi

echo ""
if [[ $PASS -eq 0 ]]; then
    echo "[clean_build] ══ PASS ══"
    exit 0
else
    echo "[clean_build] ══ FAIL — $FAIL_REASON ══"
    exit 1
fi
